<?php
//
// This is a PHP implementation of the webhook for the hiku scan device
// http://hiku.us
// 
// You can find the API documentation on github:
// https://github.com/hikuinc/hiku_shared
// In the folder API, you can find the most recent version of this API
//
// This PHP code implements a webhook which can receive the 4
// different event types and then uses the other part of the API
// to update the shopping cart in the hiku app.
// Please note that at the time of writing, the hiku app is only
// available in the US iTunes store. Don't know about the Google app store.
// https://itunes.apple.com/us/app/hiku-mobile/id721935991?mt=8
// You can order the hiku online, for example at Amazon
//
// A more detailed explanation of this code can be found in several
// blog articles:
// https://piandmore.wordpress.com/tag/hiku/
// starting at the first article:
// https://piandmore.wordpress.com/2017/11/06/online-groceries-barcodes-and-hiku/
//

//
// Start by loading default variables for database, passwords etc
//
include("MyVARS.php");
include("CommonFunctions.php");

//
// When timestamping events, we want one time for all events in this 'beep' so
// save the time and create a string version which will be used in the database.
//
$currenttime = time();
$time = strftime("%Y-%m-%d %H:%M:%S",$currenttime);

//
// For testing purposes, I created the option to enter an EAN through the url:
// http://yourdomain.com/nameofthisfile.php?ean=290000000000
// or the option to reload a file that was generated by a real hiku beep:
// http://yourdomain.com/nameofthisfile.php?file=20170101-10.11.12
// which would load the file created at 10:11:12 on 01-01-2017
//
// If you do not need to test anymore you can remove all development code.
// You will find these sections in this file and in the CommonFunctions file
// between the following 2 tags:
// #### BEGIN DEV
// #### END DEV
//
// #### BEGIN DEV
if (isset($_GET['ean'])) {
  //
  // This is a way to test what your code does for a specific ean. Pass it by loading
  // beep.php?ean=1234567890123
  // or
  // beep.php?ean=1234567890123&eventId=1
  // in your browser.
  //
  // You can pass a specific eventId if you wish with the parameter eventid.
  // If not passed, eventId EAN_INPUT_MANUALLY (non-existent in the hiku API)
  // will be used.
  //
  $eventId = isset($_GET['eventId']) ? $_GET['eventId'] : EAN_INPUT_MANUALLY;
  $postBody = '{"data": {"eventDesc": "EAN_ENTERED", "token": "'.$token.'", "eventId": '.$eventId.', "eanNotFound": "'.$_GET['ean'].'"}}';
} else if (isset($_GET['file'])) {
  //
  // During development save the events in your $dirData directory (see next if section)
  // which you can than load to retry in case you need to update your code.
  // Load it by entering this in the browser:
  // beep.php?file=20171011-12.13.14
  //
  $postBody = file_get_contents("{$dirData}{$_GET['file']}.body.txt");
} else {
  //
  // This section saves the body from the POST into a variable.
  // During development each body is also saved in a file with a timestamp as the file name
  // so you can reply the file to retest your code (see previous if section)
  //
// #### END DEV
  $postBody = file_get_contents('php://input');
// #### BEGIN DEV
  $time2 = strftime("%Y%m%d-%H.%M.%S",$currenttime);
  file_put_contents($dirData.$time2.".body.txt",$postBody);
}
// #### END DEV

//
// When we send an OK response, we can include some extra information
// which will be stored in the $replyData variable.
//
$replyData = array();

//
// We expect the body of the POST to our webhook to have content as explained
// in the API documentation
//
if (strlen($postBody)>0) {
  //
  // Convert the POST body into an array. We assume it is a json file
  //
  $hikuData = json_decode($postBody,true);
  //
  // If it is from hiku then it will start with a data section as describe in the API
  //
  if (isset($hikuData['data'])) {
    //
    // Move one layer down into the data section
    //
    $hikuData = $hikuData['data'];
    //
    // A properly formatted hiku json will have an eventId
    //
    if (isset($hikuData['eventId'])) {
      $eventId = $hikuData['eventId'];
      switch ($eventId) {
        case PRODUCT_ENTRY:
          //
          // We've received a PRODUCT_ENTRY 'beep' which we process in a function
          // We need 2 arrays as an answer so this is done through global variables
          // $beep and $replyData
          //
          hikuPRODUCT_ENTRY($hikuData);
          break;
        case EAN_NOT_FOUND:
        // #### BEGIN DEV
        case EAN_INPUT_MANUALLY:
        // #### END DEV
          //
          // We've received an EAN_NOT_FOUND 'beep' which we process in a function
          // We need 2 arrays as an answer so this is done through global variables
          // $beep and $replyData
          // During development/testing, you can also enter a EAN manually which
          // will be treated as an EAN_NOT_FOUND
          //
          hikuEAN_NOT_FOUND($hikuData);
          break;
        case DEVICE_BATTERY_LEVEL:
          //
          // We've received a DEVICE_BATTERY_LEVEL event which we process in a function
          // We need 2 arrays as an answer so this is done through global variables
          // $beep and $replyData
          //
          hikuDEVICE_BATTERY_LEVEL($hikuData);
          break;
        case DEVICE_REGISTERED:
          //
          // We've received a DEVICE_REGISTERED event which we process in a function
          // We need 2 arrays as an answer so this is done through global variables
          // $beep and $replyData
          //
          hikuDEVICE_REGISTERED($hikuData);
          break;
        default:
          $error = "HIKU:Undefined event id";
      }
    } else {
      //
      // If it was a properly formatted hiku json file, it would have a data section.
      // Apparently it doesn't so log an error
      //
      $eventId = 0;
      $error = "HIKU:No event id";
    }
  } else {
    //
    // If it was a properly formatted hiku json file, it would have a data section.
    // Apparently it doesn't so log an error
    //
    $eventId = 0;
    $error = "HIKU:Expected data field";
  }
} else {
  //
  // The webhook was called without any data in the POST body. This should not
  // happen under normal circumstances.
  //
  $eventId = 0;
  $error = "HIKU:Expected data in body";
}

//
// If we encountered an error, the $error variable will be set.
// We will send an error reply and log the error in the database.
//
if (isset($error)) {
  // #### BEGIN DEV
  sendPushMessage($error);
  // #### END DEV
  //
  // Log the error in the database
  //

  //
  // Send an error message as defined in the API
  //
  $json = array("response"=>array("status"=>"error","errMg"=>$error));
} else {
  //
  // For development purposes, you can send a push message so you can verify it works as expected
  //
  // #### BEGIN DEV
  $message = "HIKU:{$eventId}:{$beep['fullProductName']}";
  sendPushMessage($message);
  // #### END DEV
  //
  // Send an OK message with the data we gathered during processing
  //
  $json = array("response"=>array("status"=>"ok","data"=>$replyData));
}
//
// Whether it was a success or not, we send a JSON reply message.
//
$jsonstring = json_encode($json);
header('Content-type: application/json');
print $jsonstring;
?>
